parameters:
#    square_enix_rest.example.class: SquareEnix\RestBundle\Example

services:
#    square_enix_rest.example:
#        class: %square_enix_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
